### ISSUE TITLE
Notification unit test failing

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/remote-office-hours-queue#255]
@jlost, I neglected to check the unit tests when I was reviewing your PR #251. I think deleting the `delete` trigger function broke this test. It shouldn't be a big deal to fix or remove it. It may also be worth looking at the other tests to see if they should be tweaked anywhere.

```
======================================================================
ERROR: test_first_meeting_removal_bad_phone_logs_exception (officehours_api.tests.NotificationTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/unittest/mock.py", line 1325, in patched
    return func(*newargs, **newkeywargs)
  File "/usr/src/app/officehours_api/tests.py", line 130, in test_first_meeting_removal_bad_phone_logs_exception
    self.assert_twilio_exception_logged(lambda: m1.delete())
  File "/usr/src/app/officehours_api/tests.py", line 67, in assert_twilio_exception_logged
    self.assertIn('Twilio returned the following information', cm.output[0])
IndexError: list index out of range
```

**Comment by jlost** [comment]
Good catch, I tested it manually and the unit tests slipped my mind. I created #259 to prevent that from happening in the future.
