### ISSUE TITLE
`MultipleObjectsReturned` exception from `MyUserSerializer`

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/remote-office-hours-queue#341]
I happened to be looking at the production logs, and I saw this exception being thrown sometimes. This is probably something we should look into to determine whether it's significant/affecting the user experience.

```
Traceback (most recent call last): 
File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 154, in run_asgi 
result = await self.app(self.scope, self.asgi_receive, self.asgi_send) 
File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__ 
return await self.app(scope, receive, send) 
File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/asgi2.py", line 7, in __call__ 
await instance(receive, send) 
File "/usr/local/lib/python3.8/site-packages/channels/sessions.py", line 183, in __call__ 
return await self.inner(receive, self.send) 
File "/usr/local/lib/python3.8/site-packages/channels/middleware.py", line 41, in coroutine_call 
await inner_instance(receive, send) 
File "/usr/local/lib/python3.8/site-packages/channels/consumer.py", line 58, in __call__ 
await await_many_dispatch( 
File "/usr/local/lib/python3.8/site-packages/channels/utils.py", line 51, in await_many_dispatch 
await dispatch(result) 
File "/usr/local/lib/python3.8/site-packages/asgiref/sync.py", line 423, in __call__ 
ret = await asyncio.wait_for(future, timeout=None) 
File "/usr/local/lib/python3.8/asyncio/tasks.py", line 455, in wait_for 
return await fut 
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run 
result = self.fn(*self.args, **self.kwargs) 
File "/usr/local/lib/python3.8/site-packages/channels/db.py", line 14, in thread_handler 
return super().thread_handler(loop, *args, **kwargs) 
File "/usr/local/lib/python3.8/site-packages/asgiref/sync.py", line 462, in thread_handler 
return func(*args, **kwargs) 
File "/usr/local/lib/python3.8/site-packages/channels/consumer.py", line 105, in dispatch 
handler(message) 
File "/usr/src/app/officehours_api/consumers.py", line 207, in user_update 
user_data = MyUserSerializer( 
File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 562, in data 
ret = super().data 
File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 260, in data 
self._data = self.to_representation(self.instance) 
File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 529, in to_representation 
ret[field.field_name] = field.to_representation(attribute) 
File "/usr/local/lib/python3.8/site-packages/rest_framework/fields.py", line 1905, in to_representation 
return method(value) 
File "/usr/src/app/officehours_api/serializers.py", line 107, in get_my_queue 
meeting = obj.meeting_set.get() 
File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method 
return getattr(self.get_queryset(), name)(*args, **kwargs) 
File "/usr/local/lib/python3.8/site-packages/safedelete/queryset.py", line 94, in get 
return super(SafeDeleteQueryset, queryset).get(*args, **kwargs) 
File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 419, in get 
raise self.model.MultipleObjectsReturned( 
**officehours_api.models.Meeting.MultipleObjectsReturned: get() returned more than one Meeting -- it returned 2!**
```

**Comment by ssciolla** [comment]
Looking at it a bit more closely, this seems to indicate someone was assigned to two meetings. How does that happen? I didn't think that was possible.
