### ISSUE TITLE
Meetings Deleted in BlueJeans cause 500 Upon Removal

### ISSUE THREAD

**Issue by jlost** [tl-its-umich-edu/remote-office-hours-queue#41]
Meetings that have been deleted in BlueJeans will cause a 500 error when removed from Office Hours. 

Repro steps:
1. Create a queue and add an attendee with BlueJeans backend enabled (creates a Meeting)
2. Delete the created meeting from BlueJeans
3. Delete the meeting from Office Hours manage page

Stack trace:
```
Internal Server Error: /api/meetings/<id>/
--
  | Traceback (most recent call last):
  | File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
  | response = get_response(request)
  | File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
  | response = self.process_exception_by_middleware(e, request)
  | File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
  | response = wrapped_callback(request, *callback_args, **callback_kwargs)
  | File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
  | return view_func(*args, **kwargs)
  | File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
  | return self.dispatch(request, *args, **kwargs)
  | File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
  | response = self.handle_exception(exc)
  | File "/usr/local/lib/python3.8/site-packages/rest_framework_tracking/base_mixins.py", line 42, in handle_exception
  | response = super(BaseLoggingMixin, self).handle_exception(exc)
  | File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
  | self.raise_uncaught_exception(exc)
  | File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
  | raise exc
  | File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
  | response = handler(request, *args, **kwargs)
  | File "/usr/local/lib/python3.8/site-packages/rest_framework/generics.py", line 291, in delete
  | return self.destroy(request, *args, **kwargs)
  | File "/usr/local/lib/python3.8/site-packages/rest_framework/mixins.py", line 91, in destroy
  | self.perform_destroy(instance)
  | File "/usr/local/lib/python3.8/site-packages/rest_framework/mixins.py", line 95, in perform_destroy
  | instance.delete()
  | File "/usr/local/lib/python3.8/site-packages/safedelete/models.py", line 169, in delete
  | self.delete(force_policy=SOFT_DELETE, **kwargs)
  | File "/usr/local/lib/python3.8/site-packages/safedelete/models.py", line 144, in delete
  | pre_softdelete.send(sender=self.__class__, instance=self, using=using)
  | File "/usr/local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 173, in send
  | return [
  | File "/usr/local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 174, in <listcomp>
  | (receiver, receiver(signal=self, sender=sender, **named))
  | File "/usr/src/app/officehours_api/models.py", line 115, in pre_delete_meeting_signal_handler
  | backend.remove_user_meeting(instance.backend_metadata)
  | File "/usr/src/app/officehours_api/backends/bluejeans.py", line 160, in remove_user_meeting
  | self.delete_meeting(user_id, meeting_id)
  | File "/usr/src/app/officehours_api/backends/bluejeans.py", line 101, in delete_meeting
  | resp.raise_for_status()
  | File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
  | raise HTTPError(http_error_msg, response=self)
  | requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.bluejeans.com/v1/user/<user_id>/scheduled_meeting/<numeric_meeting_id>
```

**Comment by jlost** [comment]
@mfldavidson @teshsopher 
Is the best fix here to remove the ROHQ Meeting if the BlueJeans Meeting is deleted?

@teshsopher made the following comment:
>I think the case Kris mentioned where the meeting automatically ends if a participant is alone for 60 minutes is one of the cases where the meeting would end but not be finished, since some users may join too early or is waiting a long time. In these cases, removing from queue may work for hosts, but not attendees (I think remember this happening once before where an attendee joined early, but if that's already been addressed, please ignore me!)

Has this actually happened? Is it likely enough to happen that we should design for it? The alternative to deleting the ROHQ Meeting if the BJ Meeting is deleted would be to create a new BJ Meeting and update the ROHQ Meeting with it when that state is detected.

**Comment by jlost** [comment]
I think swallowing the 404 error from the BJ Meeting already being deleted and proceeding with the deletion of the ROHQ meeting is a foolproof fix for this particular case, so that's what I'll do. For now I'll gloss over the possibility that a user may try to e.g. join an already-deleted BJ Meeting, because the fix for that would be much more invasive anyway.

**Comment by jlost** [comment]
Resolved by NOT deleting BJ meetings, as old meetings remove themselves from the BJ dashboard anyway.
