### ISSUE TITLE
docker compose up now casuing error.

### ISSUE THREAD

**Issue by hanzheg** [tl-its-umich-edu/remote-office-hours-queue#590]
When run dockercompose up, we now get the error: 

remote-office-hours-queue-web-1              | Skipping OIDCAuthenticationBackend as OIDC variables were not set.
remote-office-hours-queue-web-1              | Traceback (most recent call last):
remote-office-hours-queue-web-1              |   File "/usr/src/app/manage.py", line 21, in <module>
remote-office-hours-queue-web-1              |     main()
remote-office-hours-queue-web-1              |   File "/usr/src/app/manage.py", line 17, in main
remote-office-hours-queue-web-1              |     execute_from_command_line(sys.argv)
remote-office-hours-queue-web-1              |   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
remote-office-hours-queue-web-1              |     utility.execute()
remote-office-hours-queue-web-1              |   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 382, in execute
remote-office-hours-queue-web-1              |     settings.INSTALLED_APPS
remote-office-hours-queue-web-1              |   File "/usr/local/lib/python3.10/site-packages/django/conf/__init__.py", line 102, in __getattr__
remote-office-hours-queue-web-1              |     self._setup(name)
remote-office-hours-queue-web-1              |   File "/usr/local/lib/python3.10/site-packages/django/conf/__init__.py", line 89, in _setup
remote-office-hours-queue-web-1              |     self._wrapped = Settings(settings_module)
remote-office-hours-queue-web-1              |   File "/usr/local/lib/python3.10/site-packages/django/conf/__init__.py", line 217, in __init__
remote-office-hours-queue-web-1              |     mod = importlib.import_module(self.SETTINGS_MODULE)
remote-office-hours-queue-web-1              |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
remote-office-hours-queue-web-1              |     return _bootstrap._gcd_import(name[level:], package, level)
remote-office-hours-queue-web-1              |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
remote-office-hours-queue-web-1              |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
remote-office-hours-queue-web-1              |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
remote-office-hours-queue-web-1              |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
remote-office-hours-queue-web-1              |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
remote-office-hours-queue-web-1              |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
remote-office-hours-queue-web-1              |   File "/usr/src/app/officehours/settings.py", line 299, in <module>
remote-office-hours-queue-web-1              |     EMAIL_HOST = os.getenv('EMAIL_HOST').strip()
remote-office-hours-queue-web-1              | AttributeError: 'NoneType' object has no attribute 'strip'
remote-office-hours-queue-web-1 exited with code 1

**Comment by jonespm** [comment]
This should be fixed by #559
